'use strict';

export const NAVIGATION_WELCOME = 'NAVIGATION_WELCOME';
export const NAVIGATION_ABOUT = 'NAVIGATION_ABOUT';
export const NAVIGATION_CONNECTING = 'NAVIGATION_CONNECTING';
export const NAVIGATION_DEVICE_MENU = 'NAVIGATION_DEVICE_MENU';
export const NAVIGATION_DATA_SETS = 'NAVIGATION_DATA_SETS';
export const NAVIGATION_VIEW_DATA_SET = 'NAVIGATION_VIEW_DATA_SET';
export const NAVIGATION_LIVE_DATA = 'NAVIGATION_LIVE_DATA';
export const NAVIGATION_BACK = 'NAVIGATION_BACK';

export const DEVICE_PING_START = 'DEVICE_PING_START';
export const DEVICE_PING_SUCCESS = 'DEVICE_PING_SUCCESS';
export const DEVICE_PING_FAIL = 'DEVICE_PING_FAIL';

export const DEVICE_CONNECT_START = 'DEVICE_CONNECT_START';
export const DEVICE_CONNECT_TRY = 'DEVICE_CONNECT_TRY';
export const DEVICE_CONNECT_STOP = 'DEVICE_CONNECT_STOP';
export const DEVICE_CONNECT_INFO = 'DEVICE_CONNECT_INFO';

export const DEVICE_CAPABILITIES_START = 'DEVICE_CAPABILITIES_START';
export const DEVICE_CAPABILITIES_SUCCESS = 'DEVICE_CAPABILITIES_SUCCESS';
export const DEVICE_CAPABILITIES_FAIL = 'DEVICE_CAPABILITIES_FAIL';

export const DEVICE_DATA_SETS_START = 'DEVICE_DATA_SETS_START';
export const DEVICE_DATA_SETS_SUCCESS = 'DEVICE_DATA_SETS_SUCCESS';
export const DEVICE_DATA_SETS_FAIL = 'DEVICE_DATA_SETS_FAIL';

export const DEVICE_DATA_SET_START = 'DEVICE_DATA_SET_START';
export const DEVICE_DATA_SET_SUCCESS = 'DEVICE_DATA_SET_SUCCESS';
export const DEVICE_DATA_SET_FAIL = 'DEVICE_DATA_SET_FAIL';

export const DEVICE_ERASE_DATA_SET_START = 'DEVICE_ERASE_DATA_SET_START';
export const DEVICE_ERASE_DATA_SET_SUCCESS = 'DEVICE_ERASE_DATA_SET_SUCCESS';
export const DEVICE_ERASE_DATA_SET_FAIL = 'DEVICE_ERASE_DATA_SET_FAIL';

export const EMAIL_DATA_SET_START = 'EMAIL_DATA_SET_START';
export const EMAIL_DATA_SET_SUCCESS = 'EMAIL_DATA_SET_SUCCESS';
export const EMAIL_DATA_SET_FAILURE = 'EMAIL_DATA_SET_FAILURE';
