'use strict';

export const NAVIGATION_WELCOME = 'NAVIGATION_WELCOME';
export const NAVIGATION_ABOUT = 'NAVIGATION_ABOUT';
export const NAVIGATION_CONNECTING = 'NAVIGATION_CONNECTING';
export const NAVIGATION_DEVICE_MENU = 'NAVIGATION_DEVICE_MENU';

export const DEVICE_PING_START = 'DEVICE_PING_START';
export const DEVICE_PING_SUCCESS = 'DEVICE_PING_SUCCESS';
export const DEVICE_PING_FAIL = 'DEVICE_PING_FAIL';

export const DEVICE_CONNECT_START = 'DEVICE_CONNECT_START';
export const DEVICE_CONNECT_TRY = 'DEVICE_CONNECT_TRY';
export const DEVICE_CONNECT_STOP = 'DEVICE_CONNECT_STOP';
export const DEVICE_CONNECT_INFO = 'DEVICE_CONNECT_INFO';
