@Library('conservify') _

conservifyProperties()

properties([
    disableConcurrentBuilds(),
])

timestamps {
    node () {
        stage ('git') {
            checkout scm
        }

        stage ("configuration") {
            withCredentials([file(credentialsId: 'app-android-signing-data', variable: 'APP_ANDROID_SIGNING_DATA')]) {
                sh "cp -f $APP_ANDROID_SIGNING_DATA android/app/secrets.zip && (cd android/app && unzip -o secrets.zip)"
            }
        }

        stage ('build') {
            sh """
rm -rf node_modules/*/.git

npm install

export ANDROID_HOME=/var/jenkins_home/workspace/android-sdk/android-sdk
export FIELDKIT_ENV=release

rm -rf android/app/build/outputs/apk/release/*.apk

cd android && ./gradlew assembleRelease
"""
	      }

        stage ('archive') {
            archiveArtifacts artifacts: 'android/app/build/outputs/apk/release/*.apk'
        }
    }
}
