@Library('conservify') _

properties([
    [$class: 'BuildDiscarderProperty', strategy: [$class: 'LogRotator', numToKeepStr: '5']],
    disableConcurrentBuilds(),
])

timestamps {
    node () {
        stage ('git') {
            checkout scm
        }

        stage ("configuration") {
            withCredentials([file(credentialsId: 'app-android-signing-data', variable: 'APP_ANDROID_SIGNING_DATA')]) {
                sh "cp -f $APP_ANDROID_SIGNING_DATA android/app/secrets.zip && (cd android/app && unzip -o secrets.zip)"
            }
        }

        stage ('build') {
            sh """
# rm -rf node_modules

npm install

export ANDROID_HOME=/var/jenkins_home/workspace/android-sdk/android-sdk
export FIELDKIT_ENV=release

cd android && ./gradlew assembleRelease
"""
	      }

        stage ('archive') {
            archiveArtifacts artifacts: 'android/app/build/outputs/apk/*.apk'
        }
    }
}
