@Library('conservify') _

conservifyProperties()

properties([
    disableConcurrentBuilds(),
])

timestamps {
    node () {
        try {
            stage ('git') {
                checkout scm
            }

            stage ("configuration") {
            }

            stage ('build') {
              sh """
export PATH=$PATH:$HOME/tools/node/bin

pwd

ls -alh ../

if [ ! -d ../app-protocol ]; then
	git clone https://github.com/fieldkit/app-protocol.git ../app-protocol
else
	(cd ../app-protocol && git pull)
fi
if [ ! -d ../data-protocol ]; then
	git clone https://github.com/fieldkit/data-protocol.git ../data-protocol
else
	(cd ../data-protocol && git pull)
fi
if [ ! -d ../atlas ]; then
	git clone https://github.com/fieldkit/atlas.git ../atlas
else
	(cd ../atlas && git pull)
fi

rm -rf node_modules/*/.git

npm install

security list-keychains

security lock-keychain login.keychain

security unlock-keychain -p "asdfasdf" login.keychain

security show-keychain-info login.keychain

cd ios

xcodebuild -project FieldKit.xcodeproj -scheme FieldKit -sdk iphoneos -configuration Release archive -archivePath $PWD/build/FieldKit.xcarchive

xcodebuild -exportArchive -archivePath $PWD/build/FieldKit.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build

cd ..
"""
            }

            stage ('archive') {
                archiveArtifacts artifacts: 'ios/build/*.ipa'
            }

            notifySuccess()
        }
        catch (Exception e) {
            notifyFailure()
            throw e;
        }
    }
}
