export const ATLAS_CALIBRATION_BEGIN = "ATLAS_CALIBRATION_BEGIN";
export const ATLAS_CALIBRATION_END = "ATLAS_CALIBRATION_END";

export const DEVICE_ATLAS_SENSOR_READING_START =
    "DEVICE_ATLAS_SENSOR_READING_START";
export const DEVICE_ATLAS_SENSOR_READING_SUCCESS =
    "DEVICE_ATLAS_SENSOR_READING_SUCCESS";
export const DEVICE_ATLAS_SENSOR_READING_FAIL =
    "DEVICE_ATLAS_SENSOR_READING_FAIL";

export const DEVICE_ATLAS_SENSOR_SET_PROBE_TYPE_START =
    "DEVICE_ATLAS_SENSOR_SET_PROBE_TYPE_START";
export const DEVICE_ATLAS_SENSOR_SET_PROBE_TYPE_SUCCESS =
    "DEVICE_ATLAS_SENSOR_SET_PROBE_TYPE_SUCCESS";
export const DEVICE_ATLAS_SENSOR_SET_PROBE_TYPE_FAIL =
    "DEVICE_ATLAS_SENSOR_SET_PROBE_TYPE_FAIL";

export const DEVICE_ATLAS_SENSOR_CALIBRATE_START =
    "DEVICE_ATLAS_SENSOR_CALIBRATE_START";
export const DEVICE_ATLAS_SENSOR_CALIBRATE_SUCCESS =
    "DEVICE_ATLAS_SENSOR_CALIBRATE_SUCCESS";
export const DEVICE_ATLAS_SENSOR_CALIBRATE_FAIL =
    "DEVICE_ATLAS_SENSOR_CALIBRATE_FAIL";

export const ATLAS_READ_SENSOR_START = "ATLAS_READ_SENSOR_START";
export const ATLAS_READ_SENSOR_STOP = "ATLAS_READ_SENSOR_STOP";
export const ATLAS_READ_SENSOR_READING = "ATLAS_READ_SENSOR_READING";

export const ATLAS_CALIBRATION_TEMPERATURE_SET =
    "ATLAS_CALIBRATION_TEMPERATURE_SET";
export const ATLAS_CALIBRATION_PROBE_TYPE_SET =
    "ATLAS_CALIBRATION_PROBE_TYPE_SET";
